spring.application.name=alquiler_vehiculos


# Puerto del servidor Spring Boot
server.port=8080

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Conexión a la Base de Datos MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bd_alquiler_vehiculos?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

# Locale configuration
spring.web.locale=es_PE
spring.web.locale-resolver=fixed